# Codecov Configuration
# https://docs.codecov.io/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "50...100"

  status:
    project:
      default:
        target: 50%
        threshold: 5%
        informational: true
    patch:
      default:
        target: 60%
        threshold: 5%
        informational: true

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

ignore:
  - "**/*.g.dart"
  - "**/*.freezed.dart"
  - "**/generated/**"
  - "test/**"
  - "integration_test/**"
  - "lib/main.dart"

flags:
  unittests:
    paths:
      - lib/
    carryforward: true
