import 'dart:io';

import 'package:dart_frog/dart_frog.dart';

import '../../../../lib/core/core.dart';
import '../../../../lib/features/eggs/data/repositories/egg_repository_impl.dart';
import '../../../../lib/features/eggs/domain/entities/egg_record.dart';
import '../../../../lib/features/eggs/domain/usecases/egg_usecases.dart';

/// Handler for /api/v1/eggs
/// GET - Get all egg records for authenticated user
/// POST - Create a new egg record
Future<Response> onRequest(RequestContext context) async {
  return switch (context.request.method) {
    HttpMethod.get => _getEggRecords(context),
    HttpMethod.post => _createEggRecord(context),
    _ => Future.value(
        Response(statusCode: HttpStatus.methodNotAllowed),
      ),
  };
}

/// GET /api/v1/eggs
Future<Response> _getEggRecords(RequestContext context) async {
  try {
    // Get user ID from auth middleware (would be set by middleware)
    final userId = context.request.headers['x-user-id'];
    if (userId == null) {
      return Response.json(
        statusCode: HttpStatus.unauthorized,
        body: {'error': 'Unauthorized'},
      );
    }

    // Get query parameters for filtering
    final queryParams = context.request.uri.queryParameters;
    final startDate = queryParams['start_date'];
    final endDate = queryParams['end_date'];

    final repository = EggRepositoryImpl(SupabaseClientManager.client);

    final Result<List<EggRecord>> result;
    if (startDate != null && endDate != null) {
      final useCase = GetEggRecordsInRange(repository);
      result = await useCase(
        GetEggRecordsInRangeParams(
          userId: userId,
          startDate: startDate,
          endDate: endDate,
        ),
      );
    } else {
      final useCase = GetEggRecords(repository);
      result = await useCase(GetEggRecordsParams(userId: userId));
    }

    return result.fold(
      onSuccess: (records) => Response.json(
        body: {
          'data': records.map((r) => r.toJson()).toList(),
          'count': records.length,
        },
      ),
      onFailure: (failure) => Response.json(
        statusCode: HttpStatus.internalServerError,
        body: {'error': failure.message},
      ),
    );
  } catch (e) {
    return Response.json(
      statusCode: HttpStatus.internalServerError,
      body: {'error': e.toString()},
    );
  }
}

/// POST /api/v1/eggs
Future<Response> _createEggRecord(RequestContext context) async {
  try {
    final userId = context.request.headers['x-user-id'];
    if (userId == null) {
      return Response.json(
        statusCode: HttpStatus.unauthorized,
        body: {'error': 'Unauthorized'},
      );
    }

    final body = await context.request.json() as Map<String, dynamic>;

    // Validate required fields
    if (body['date'] == null || body['eggs_collected'] == null) {
      return Response.json(
        statusCode: HttpStatus.badRequest,
        body: {'error': 'Missing required fields: date, eggs_collected'},
      );
    }

    final now = DateTime.now().toUtc();
    final record = EggRecord(
      id: '', // Will be generated by database
      userId: userId,
      date: body['date'] as String,
      eggsCollected: body['eggs_collected'] as int,
      eggsBroken: (body['eggs_broken'] as int?) ?? 0,
      eggsConsumed: (body['eggs_consumed'] as int?) ?? 0,
      notes: body['notes'] as String?,
      createdAt: now,
      updatedAt: now,
    );

    final repository = EggRepositoryImpl(SupabaseClientManager.client);
    final useCase = CreateEggRecord(repository);
    final result = await useCase(CreateEggRecordParams(record: record));

    return result.fold(
      onSuccess: (created) => Response.json(
        statusCode: HttpStatus.created,
        body: {'data': created.toJson()},
      ),
      onFailure: (failure) {
        final statusCode = failure is ValidationFailure
            ? HttpStatus.badRequest
            : HttpStatus.internalServerError;
        return Response.json(
          statusCode: statusCode,
          body: {'error': failure.message},
        );
      },
    );
  } catch (e) {
    return Response.json(
      statusCode: HttpStatus.internalServerError,
      body: {'error': e.toString()},
    );
  }
}
